version: 0.94.{build}
os: Visual Studio 2017
configuration:
- Debug
- Release
- Checked
platform:
- Win32
- x64
before_build:
- set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%
build:
  project: src/msf_vc141.sln
  verbosity: minimal