version: 0.94.{build}
os: Visual Studio 2015
configuration:
- Debug
- Release
- Checked
platform:
- Win32
- x64
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: src/msf_vc140.sln
  verbosity: minimal